# Generated by Django 5.0 on 2024-09-18 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='idade',
        ),
    ]
