# Generated by Django 5.0 on 2024-10-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_descricao_curta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_b', models.CharField(max_length=255, verbose_name='Tipo de Bebida')),
                ('informacao_curta', models.TextField(max_length=255, verbose_name='Descr.Bebida')),
                ('informacao_longa', models.TextField(verbose_name='Detalhes da Bebida')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto_imagens/%Y/%m/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('preco_marketing_b', models.FloatField(verbose_name='Preço')),
                ('preco_promocional_b', models.FloatField(default=0, verbose_name='Preço Promo.')),
            ],
        ),
        migrations.CreateModel(
            name='VariacaoBebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_b', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tamanho')),
                ('preco_marketing_b', models.FloatField()),
                ('preco_promocional_b', models.FloatField(default=0)),
                ('estoque_b', models.PositiveIntegerField(default=1, verbose_name='Estoque')),
                ('produto_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.bebida', verbose_name='Bebidas')),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
            },
        ),
    ]
