# Generated by Django 5.0 on 2024-10-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_bebida_variacaobebida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacaobebida',
            options={'verbose_name': 'Variação de Bebida', 'verbose_name_plural': 'Variações de Bebidas'},
        ),
    ]
