# Generated by Django 5.0 on 2024-10-16 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_variacaobebida_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=2),
        ),
        migrations.CreateModel(
            name='Borda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Borda')),
                ('preco', models.FloatField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Borda',
                'verbose_name_plural': 'Tipo de Borda',
            },
        ),
    ]
