# Generated by Django 5.0 on 2024-10-17 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_produto_3_variacao_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borda',
            options={'verbose_name': 'Borda', 'verbose_name_plural': 'Pizzas - Tipo de Borda'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AlterModelOptions(
            name='produto_3',
            options={'verbose_name': 'Produtos', 'verbose_name_plural': 'Pizzas Doces'},
        ),
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Pizzas - Variações'},
        ),
        migrations.AlterModelOptions(
            name='variacao_2',
            options={'verbose_name': 'Variação 2', 'verbose_name_plural': 'Pizzas Doces - Variações'},
        ),
        migrations.AlterField(
            model_name='variacao_2',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto_3', verbose_name='Pizzas Doces'),
        ),
    ]
