# Generated by Django 5.0 on 2024-10-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('produto', '0007_alter_borda_options_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borda',
            name='produto',
        ),
        migrations.AddField(
            model_name='borda',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='borda',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
