# Generated by Django 5.0 on 2024-10-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_remove_borda_produto_borda_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaobebida',
            name='preco_marketing_b',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variacaobebida',
            name='preco_promocional_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
