# Generated by Django 5.0 on 2024-10-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_variacaobebida_preco_marketing_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaobebida',
            name='preco_marketing_b',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='variacaobebida',
            name='preco_promocional_b',
            field=models.FloatField(default=0),
        ),
    ]
