# Generated by Django 5.0 on 2024-10-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_alter_variacaobebida_preco_marketing_b_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variacao_2',
            new_name='Alteracao',
        ),
    ]
