# Generated by Django 5.0 on 2024-10-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_rename_variacao_2_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Produtos'),
        ),
    ]
