# Generated by Django 5.0 on 2024-10-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_alter_produto_descricao_curta_alter_produto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao_curta',
            field=models.TextField(max_length=100, verbose_name='Descr.Produto'),
        ),
    ]
