# Generated by Django 5.0 on 2024-10-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_alter_produto_descricao_curta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao_curta',
            field=models.TextField(max_length=255, verbose_name='Descr.Produto'),
        ),
    ]
