# Generated by Django 5.0 on 2024-10-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_alter_produto_descricao_curta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.CharField(max_length=50)),
            ],
        ),
    ]
