# Generated by Django 5.0 on 2024-11-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0016_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma_pagamento',
            name='valor_dinheiro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
