# Generated by Django 5.0 on 2024-11-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0017_forma_pagamento_valor_dinheiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='informacao_curta',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descr.Bebida'),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='informacao_longa',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Bebida'),
        ),
    ]
