# Generated by Django 5.0 on 2024-10-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_itempedido_pedido_alter_itempedido_preco_and_more'),
        ('produto', '0005_alter_produto_tipo_borda'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='borda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.borda'),
        ),
    ]
