# Generated by Django 5.0 on 2024-10-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_pedido_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('C', 'Em preparação'), ('R', 'Reprovado'), ('P', 'Pendente'), ('E', 'Saiu para Entrega'), ('F', 'Finalizado')], default='C', max_length=1),
        ),
    ]
