# Generated by Django 5.0 on 2024-10-31 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_alter_pedido_status'),
        ('produto', '0016_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.forma_pagamento'),
        ),
    ]
